version: "3"

tasks:
  run:
    desc: "Run Go app inside Docker"
    cmds:
      - docker-compose run --rm app go run main.go

  dev:
    desc: "Run hot reload inside Docker"
    cmds:
      - docker-compose run --rm app air

  build:
    desc: "Build Docker image"
    cmds:
      - docker-compose build

  docker-up:
    desc: "Start containers"
    cmds:
      - docker-compose up -d

  docker-down:
    desc: "Stop containers"
    cmds:
      - docker-compose down
